config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "contacts#index"
  get "/create_contact", to: "contacts#create"

  get "/delete_contact", to: "contacts#delete"

  get "/view_contact", to: "contacts#show"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    if params["page_token"]
      page_token = params["page_token"]
    else
      page_token = nil
    end

    connector_response = HTTP.basic_auth(:user => "arek", :pass => ENV["PASSWORD"]).get("http://localhost:3000/contacts", json: { page_token: page_token })

    connector_result = MultiJson.load(connector_response.body.to_s) 
    @next_page_token = connector_result["next_page_token"]
    @contacts = connector_result["data"]   
  end

  def create
    connector_response = HTTP.basic_auth(:user => "arek", :pass => ENV["PASSWORD"]).post("http://localhost:3000/contacts", json: { "type": params["type"], "name": params["name"], "lastname": params["lastname"], "mobile": params["mobile"], "email": params["email"], "phone": params["phone"], "website": params["website"] })

    redirect_to action: "index"
  end

  def delete
    connector_response = HTTP.basic_auth(:user => "arek", :pass => ENV["PASSWORD"]).delete("http://localhost:3000/contacts", json: { "id": params["id"] })

    redirect_to action: "index"
  end

  def show
    connector_response = HTTP.basic_auth(:user => "arek", :pass => ENV["PASSWORD"]).get("http://localhost:3000/contacts/#{params['id']}", json: { "id": params["id"] })

    connector_result = MultiJson.load(connector_response.body.to_s) 
    
    @contact = connector_result
  end




end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <form action="/create_contact" >
      <input type="hidden" name="type" value="<%= "person" %>">
        <label for="name">  <p class="font-weight-bold">Add person to contact list</p> </label><br>
        <input type="string" class="form-control" name="name" placeholder="Enter first name">
        <p></p>
        <input type="string" class="form-control" name="lastname" placeholder="Enter last name">
        <p></p>
        <input type="string" class="form-control" name="mobile" placeholder="Enter mobile number">
        <p></p>
        <input type="string" class="form-control" name="email" placeholder="Enter email">
        <p></p>
        <button type="submit" style="float: right;" class="btn btn-info">Submit</button>
      </form>
    </div>   
    <div class="col">
      <form action="/create_contact" >
        <label for="name">  <p class="font-weight-bold">Add company to contact list</p> </label><br>
        <input type="string" class="form-control" name="name" placeholder="Enter company name">
        <p></p>
        <input type="string" class="form-control" name="phone" placeholder="Enter phone number">
        <p></p>
        <input type="string" class="form-control" name="website" placeholder="Enter website adress">
        <p></p>
        <button type="submit" style="float: right;" class="btn btn-info">Submit</button>
      </form>
    </div>   
  </div>
</div>
<p></p>

<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <p class="font-weight-bold">Contact type</p>
    </div>
    <div class="col-sm-2">
      <p class="font-weight-bold">Name</p>
    </div>
    <div class="col-sm-2">
      <p class="font-weight-bold">Phone number</p>
    </div>
    <div class="col-sm-3">
      <p class="font-weight-bold">Email/ Webesite</p>
    </div>
  </div>
</div>
<div class="container"> 
  <% @contacts.each do |contact| %>
    <div class="row"> 
      <div class="col-sm-2">
        <%= contact["contact_type"] %>
      </div>
      <div class="col-sm-2">
        <%= contact["name"] %> <%= contact["lastname"] %> 
      </div>
      <div class="col-sm-2">
        <% if contact["contact_type"] == "person" %>
          <%= contact.dig("means_of_contact", "mobile")&.join("") %>
        <% elsif contact["contact_type"] == "company" %>
          <%= contact.dig("means_of_contact", "phone")&.join("") %>
        <% end %>
      </div>
      <div class="col-sm-3">
        <% if contact["contact_type"] == "person" %>
          <%= contact.dig("means_of_contact", "email")&.join("") %>
        <% elsif contact["contact_type"] == "company" %>
          <%= contact.dig("means_of_contact", "website")&.join("") %> 
        <% end %>
      </div>
      <div class="col-sm-auto">
        <form class="form-inline" action="/delete_contact" style="display: inline;">
          <input type="hidden" name="id" value="<%= contact["contact_id"] %>">
          <button type="submit" class="btn btn-outline-dark btn-sm">Delete contact</button>
        </form>
        <%= link_to "Show contact", view_contact_path(id: contact["contact_id"]), method: "get", class: "btn btn-primary", target: "_blank" %>    
      </div>
    </div>  
  <% end %>
    <p></p>
    <div class="col">
      <form class="form-inline" method="GET" style="display: inline;">
        <input type="hidden" name="page_token" value="<%= @next_page_token %>">
        <button type="submit" style="float: right;" class="btn btn-success">Next page</button>
      </form>
    </div>

</div> 

app/views/contacts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <p class="font-weight-bold">Contact type</p>
    </div>
    <div class="col-sm-2">
      <p class="font-weight-bold">Name</p>
    </div>
    <div class="col-sm-2">
      <p class="font-weight-bold">Phone number</p>
    </div>
    <div class="col-sm-3">
      <p class="font-weight-bold">Email/ Webesite</p>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <%= @contact["contact_type"] %>
    </div>
    <div class="col-sm-2">
      <%= @contact["name"] %> <%= @contact["lastname"] %> 
    </div>
    <div class="col-sm-2">
      <%= @contact.dig("means_of_contact", "mobile")&.join("") %> <%= @contact.dig("means_of_contact", "phone")&.join("") %>
    </div>
    <div class="col-sm-3">
      <%= @contact.dig("means_of_contact", "email")&.join("") %> <%= @contact.dig("means_of_contact", "website")&.join("") %> 
    </div>
  </div>
</div>

app/views/home/home.html.erb
<div class="container">
  <div class="row">
 Siema 
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>client app</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="<%=  %>">client app</a>
  </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>